version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: satya-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: satya_db

  redis:
    image: redis:7-alpine
    container_name: satya-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: satya-ai-service
    ports:
      - "8000:8000"
    environment:
      - AI_SERVICE_KEY=${AI_SERVICE_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./ai-service:/app
      - ai_models:/root/.cache

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satya-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/satya_db
      - REDIS_URL=redis://redis:6379
      - AI_SERVICE_HOST=http://ai-service:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
      - ai-service
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules

volumes:
  mongodb_data:
  redis_data:
  ai_models:
